version: '3.7'

services:
  dev:
    image: node:latest
    working_dir: /app
    tty: true
    environment:
      - DB_IN_MEMORY
      - DEBUG
      - POSTGRES_DBNAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    links:
      - postgres
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres:
